# Generated by Django 4.2.19 on 2025-03-11 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Film',
            new_name='Films',
        ),
        migrations.RenameField(
            model_name='films',
            old_name='created_at',
            new_name='created',
        ),
    ]
