# Generated by Django 4.2.19 on 2025-03-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_rename_film_films_rename_created_at_films_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='trailer',
            field=models.URLField(null=True),
        ),
    ]
