# Generated by Django 4.2.19 on 2025-03-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_films_trailer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='films',
            options={'verbose_name': 'фильм', 'verbose_name_plural': 'фильмы'},
        ),
        migrations.AlterField(
            model_name='films',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='укажите дату выхода'),
        ),
        migrations.AlterField(
            model_name='films',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='укажите описание фильма'),
        ),
        migrations.AlterField(
            model_name='films',
            name='director',
            field=models.CharField(max_length=100, null=True, verbose_name='укажите режисера'),
        ),
        migrations.AlterField(
            model_name='films',
            name='genre',
            field=models.CharField(choices=[('Ужасы', 'Ужасы'), ('Комедия', 'Комедия')], max_length=10, null=True, verbose_name='укажите жанр'),
        ),
        migrations.AlterField(
            model_name='films',
            name='image',
            field=models.ImageField(null=True, upload_to='films/', verbose_name='загрузите фото'),
        ),
        migrations.AlterField(
            model_name='films',
            name='price',
            field=models.FloatField(null=True, verbose_name='укажите цену'),
        ),
        migrations.AlterField(
            model_name='films',
            name='time',
            field=models.TimeField(null=True, verbose_name='укажите время'),
        ),
        migrations.AlterField(
            model_name='films',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='укажите название'),
        ),
        migrations.AlterField(
            model_name='films',
            name='trailer',
            field=models.URLField(null=True, verbose_name='вставьте ссылку на трейлер'),
        ),
    ]
