# Generated by Django 4.2.19 on 2025-03-14 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'отзыв', 'verbose_name_plural': 'отзывы'},
        ),
        migrations.AlterField(
            model_name='reviews',
            name='choice_film',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='films.films', verbose_name='выберите фильм'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='укажите дату выхода'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='укажите описание фильма'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='grade',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10, null=True, verbose_name='Поставьте оценку'),
        ),
    ]
